version: 2

sources:
  - name: ga4
    database: "{{ env_var('DBT_PROJECT') }}"
    schema: "{{ env_var('DBT_DATASET') }}"
    tables:
      - name: events
        identifier: events_* # Scan across all sharded event tables. Use the 'start_date' variable to limit this scan
        description: Main events table exported by GA4. Sharded by date. 

#      - name: events_intraday
#        identifier: events_intraday_*
#        description: Intraday events table which is optionally exported by GA4. Always contains events from the current day.
